module.exports = {
    "Opportunity_1" : {
           "name" : 'Regression12',
           "acc_name" : 'a',
           "lead_name" : 'b',
           "rli_name" : 'Regression123',
           "product" : 'Do not use - gpp gsb4',
           "date" : '2018-11-08',
           "amount" : '70000',
           "type" : 'new contract',
           "competitor" : 'Abea'
       },
       "Oppurtunity_2" : {
        "name" : 'Regression12',
        "acc_name" : 'a',
        "lead_name" : 'b',
        "rli_name" : 'Regression123',
        "product" : 'BYS99',
        "date" : '2018-11-08',
        "amount" : '70000',
        "type" : 'new contract',
        "competitor" : 'Abea'

       },
       "typecount" : [6,4,3,6,5,2,1],
       "products":["BYS99" ,"BZU99",
       "BZZB0" ,
       "BYDQ0" ,
       "BXC99" ,
       "BTLC0"],
    "Rli" : {
       "name" : 'Regression12',
       "oppurtunity" : 'a',
       "date" : '2018-11-08',
       "dollars" : '70000',
       "product" : 'cams',
       "type" : 'new',
       "competitor" : 'Abea'
      },
    "Rli_Oppor" : {
           "name" : 'Regression12',
           "acc_name" : 'a',
           "lead_name" : 'b',
           "rli_name" : 'Regression123',
           "product" : 'cams',
           "date" : '2018-11-08',
           "amount" : '70000',
           "type" : 'new',
           "competitor" : 'Abea'
       },
   "Assert" : [
         [ 'Superior demo, ease of use', 
               'Superior pricing', 
               'Superior terms', 
               'Superior functionality', 
               'Integrated solution, comprehensive suite', 
               'Better relationship with customer'],
          ['Business priority changed', 
               'Client took “in-house”', 
               'Delayed indefinitely', 
               'New client management',  
               'Required funding not avail'],
          ['Bid resources not available',
               'Duplicate opportunity', 
               'Entered in Error', 
               'Too old to pursue', 
               'Client unresponsive to our efforts', 
               'Low odds of winning', 
               'Low priority vs other deals']
   ],
   "ContractInput" :["New contract",
         "New Logo",
         "Extension/Renewal",
     "PCR/Expansion",
     "Request for Service",
    "Pay as you go",
     "One Time Charge"],
    "contract" : 
             [ ["One Time Charge",
                    "One Time Charge",
                    "One Time Charge",
                    "One Time Charge",
                    "One Time Charge",
                    "One Time Charge",],
              ["SaaS New Logo Booking",
                    "SaaS Contract Extension",
                    "SaaS Expansion Booking",
                    "SaaS New Logo Booking",
                    "SaaS Pay As You Go",
                    "Saas New Logo Booking"],
              ["Lab Services",
                    "Lab Services",
                    "Lab Services",
                    "Lab Services",
                    "Lab Services",
                    "Lab Services",],
              ["New Logo (IS)",
                    "Extension/Renewal (IS)",
                    "Expansion (IS)",
                    "PCR/RFS (IS)",
                    "Pay As You Go (IS)",
                    "New Contract (IS)"],
             ["New Logo (GBS)",
                    "Extension/Renewal (GBS)",
                    "Expansion (GBS)",
                    "PCR/RFS (GBS)",
                    "Pay As You Go (IS)",
                    "New Logo (GBS)"],
             ["New Logo (GBS)",
                    "Extension/Renewal (TSS)",
                    "New Contract (TSS)",
                    "New Contract (TSS)",
                    "New Contract (TSS)",
                    "New Contract (TSS)"]]
         
       
}
