module.exports={
 
    "login" : {
               // "button" : "a[name=login_form_button]",//int01
                "button" : "a[name=external_login_button]",//sandbox
                "user"  :  "input[name=username]",
                "pass" :  "input[name=password]",
               // "signin" :  "a[name=login_button]",//int01
                "signin" : "#btn_signin",//sandbox
                "alertcancel" : "#alerts > div > div > button",
                "alertmessage" : "#alerts > div > div > span",
                "dash" : "#content > div > div > div > div > div > div > div > h1 > span:nth-child(1) > span > div" ,
                "Quick_create" : "#createList > div > button",
        },
    "oppty" :{  
                "straight" : "#header > div > div > div > div.module-list > ul > li:nth-child(4) > span > a",
                "straight_create" : "#content > div > div > div.main-pane.span8 > div:nth-child(1) > div > h1 > div > span:nth-child(1) > a",
                "q_create" :"#createList > div > div > ul > li:nth-child(2) > span > a",
                "header" : "#header > div > div > div > div.module-list > ul > li:nth-child(4) > span > a",
                "drop" : "#header > div > div > div > div.module-list > ul > li:nth-child(4) > span > button",
                "create" : "#header > div > div > div > div.module-list > ul > li:nth-child(4) > span > div > ul > li:nth-child(1) > a",
                "name" : "#drawers > div.drawer.active > div > div.main-pane.span8 > div > div > div.record.tab-layout > div > div > div:nth-child(1) > div:nth-child(1) > div.span6.record-cell.edit > span > span > input",
                "acc_name" : "div[id^=panel_bodyview] > div:nth-child(2) > div.span6.record-cell.edit > span > span > div > a > span:nth-child(1)",
                "lead_name" : "div[id^=panel_bodyview] > div:nth-child(4) > div:nth-child(1) > span > span > div > a > span:nth-child(1)",
                "rli" : {
                          "name" : "#drawers > div > div > div.main-pane.span8 > div.subpanels-layout.ui-sortable > div > ul > li > div.flex-list-view.right-actions.scroll-width > div > table > tbody > tr > td:nth-child(1) > span > input",
                          "product" : "#drawers > div > div > div.main-pane.span8 > div.subpanels-layout.ui-sortable > div > ul > li > div.flex-list-view.right-actions.scroll-width > div > table > tbody > tr > td:nth-child(2) > span > div > a > span:nth-child(1)",
                          "date" : "#drawers > div > div > div.main-pane.span8 > div.subpanels-layout.ui-sortable > div > ul > li > div.flex-list-view.right-actions.scroll-width > div > table > tbody > tr > td:nth-child(3) > span > div > div > input",
                          "amt" : "#drawers > div > div > div.main-pane.span8 > div.subpanels-layout.ui-sortable > div > ul > li > div.flex-list-view.right-actions.scroll-width > div > table > tbody > tr > td:nth-child(4) > span > div > input",
                          "type" : "#drawers > div > div > div.main-pane.span8 > div.subpanels-layout.ui-sortable > div > ul > li > div.flex-list-view.right-actions.scroll-width > div > table > tbody > tr > td:nth-child(7) > span > div > a >span:nth-child(1)",
                          "competitor" : "#drawers > div > div > div.main-pane.span8 > div.subpanels-layout.ui-sortable > div > ul > li > div.flex-list-view.right-actions.scroll-width > div > table > tbody > tr > td:nth-child(8) > span > div > ul > li > input",
                          "competitor_click" : "#select2-drop > ul > li:nth-child(1) > div",
                        },
                "save" : "#drawers > div[class='drawer active'] > div > div.main-pane.span8 > div:nth-child(1) > div > div.headerpane > h1 > div > span:nth-child(3) > a",
                "search" : "#content > div > div > div.main-pane.span8 > div:nth-child(2) > div.search-filter > div.control-group > div > div.filter-view.search > div > input",   
        },
                "dropdown" : "#header > div > div > div > div.module-list > ul > li:nth-child(11) > span > a",
                "view" : "#header > div > div > div > div.module-list > ul > li:nth-child(11) > span > div > ul > li:nth-child(1) > a",
                "search" : "#content > div > div > div.main-pane.span8 > div > div:nth-child(2) > div.search-filter > div.control-group > div > div > div > input",//tr from last has nth
                "firstchild" :"#content > div > div > div.main-pane.span8 > div > div:nth-child(2) > div.main-content > div > div.flex-list-view.left-actions.right-actions.scroll-width > div.flex-list-view-content > table > tbody > tr > td:nth-child(2) > span > div > a",
               "test_save" : "a[name=save_button]",
                "rli": {    
                        "q_create" : "#createList > div > div > ul > li:nth-child(10) > span > a",
                        "header" : "#header > div > div > div > div.module-list > ul > li:nth-child(5) > span > a",
                        "dropdown" : "#header > div > div > div > div.module-list > ul > li:nth-child(5) > span > button",
                        "view" : "#header > div > div > div > div.module-list > ul > li:nth-child(5) > span > div > ul > li:nth-child(2) > a",
                        "create" : "#header > div > div > div > div.module-list > ul > li:nth-child(5) > span > div > ul > li:nth-child(1) > a",
                        "sales_stage" :"div[id^=panel_bodyview] > div:nth-child(3) > div:nth-child(1) > div",
                        "lost" : "div[id^='panel_bodyview'] > div:nth-child(3) > div:nth-child(1) > span > span > div > a > span:nth-child(1)",
                        "lost_category" : "div[id^=panel_bodyview] > div:nth-child(3) > div:nth-child(2)",
                        "lost_cat" : "div[id^=panel_bodyview] > div:nth-child(3) > div:nth-child(2) > span > span > div > a > span:nth-child(1)",
                        "reason_lost" : "div[id^=panel_bodyview]> div:nth-child(4) > div.span6.record-cell.edit",
                        "rea_los" :"div[id^=panel_bodyview] > div:nth-child(4) > div.span6.record-cell.edit > span > span > div > a > span:nth-child(1)",
                        "name" : "#drawers > div > div > div:nth-child(1) > div:nth-child(1) > div > div:nth-child(1) > h1 > span:nth-child(2) > span > span:nth-child(2) > span > input",
                        "oppurtunity" : "div[id^='panel_bodyview'] > div:nth-child(1) > div:nth-child(1) > span > span > div > a > span:nth-child(1)",
                        "date" : "div[id^='panel_bodyview'] > div:nth-child(2) > div:nth-child(1) > span > span > div > div > input",
                        "dollars" : "div[id^='panel_bodyview'] > div:nth-child(2) > div:nth-child(2) > span > span > div > input",
                        "product" : "div[id^='panel_bodyview'] > div:nth-child(5) > div:nth-child(1) > span > span > div > a > span:nth-child(1)",
                        "type" : "div[id^='panel_bodyview'] > div:nth-child(6) > div:nth-child(2) > span > span > div > a > span:nth-child(1)",
                        "comp_input" : "div[id^='panel_bodyview'] > div:nth-child(8) > div:nth-child(1) > span > span > div > ul > li > input ",
                        "competitor" : "#select2-drop > ul > li:nth-child(1) > div",
                        "create_save":"#drawers > div > div > div.main-pane.span8 > div:nth-child(1) > div > div.headerpane > h1 > div > span:nth-child(3) > a",
                        "save" : "#content > div > div > div.main-pane.span8 > div:nth-child(1) > div > div.headerpane > h1 > div > span:nth-child(3) > a",
                        "ignoreduplicate" : "#drawers > div > div > div.main-pane.span8 > div:nth-child(1) > div > div.headerpane > h1 > div > span:nth-child(4) > a",
                        "search" : "#content > div > div > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div > div:nth-child(1) > div > input",
                        "firstchild" : "#content > div > div > div.main-pane.span8 > div:nth-child(2) > div.main-content > div:nth-child(2) > div.flex-list-view.left-actions.right-actions.scroll-width > div.flex-list-view-content > table > tbody > tr:nth-child(1) > td:nth-child(2) > span > div > a",//tr from last has nth
                        "edit" : "#content > div > div > div.main-pane.span8 > div:nth-child(1) > div > div.headerpane > h1 > div > span.fieldset.actions.detail.btn-group > span > a",
                        "lostvalue" : "div[id^=panel_bodyview] > div:nth-child(3) > div:nth-child(2) > span.normal.index > span > div",
                        "reasonvalue" : "div[id^=panel_bodyview] > div:nth-child(4) > div:nth-child(2) > span.normal.index > span > div",
                        "cancel" : "#content > div > div > div.main-pane.span8 > div:nth-child(1) > div > div.headerpane > h1 > div > span:nth-child(2) > a",
                        "sales_pencil" : "div[id^='panel_bodyview'] > div:nth-child(3) > div:nth-child(1) > span.record-edit-link-wrapper",
                        "lost_pencil" : "div[id^='panel_bodyview'] > div:nth-child(3) > div:nth-child(2) > span.record-edit-link-wrapper",
                        "reason_pencil" : "div[id^='panel_bodyview'] > div:nth-child(4) > div:nth-child(2) > span.record-edit-link-wrapper",
                        "action_drop" : "#content > div > div > div.main-pane.span8 > div:nth-child(2) > div.main-content > div:nth-child(2) > div.flex-list-view.left-actions.right-actions.scroll-width > div.flex-list-view-content > table > tbody > tr:nth-child(1) > td:nth-child(20) > span > div:nth-child(1) > span > a",
                        "action_edit" : "#content > div > div > div.main-pane.span8 > div:nth-child(2) > div.main-content > div:nth-child(2) > div.flex-list-view.left-actions.right-actions.scroll-width.no-touch-scrolling > div.flex-list-view-content > table > tbody > tr:nth-child(1) > td:nth-child(20) > span > div:nth-child(1) > span > ul > li:nth-child(1) > span > a",
                        "action_lost_span" :"#content > div > div > div.main-pane.span8 > div:nth-child(2) > div.main-content > div:nth-child(2) > div.flex-list-view.left-actions.right-actions.scroll-width > div.flex-list-view-content > table > tbody > tr.single.tr-inline-edit > td:nth-child(8) > span",
                        "action_lost" : "#content > div > div > div.main-pane.span8 > div:nth-child(2) > div.main-content > div:nth-child(2) > div.flex-list-view.left-actions.right-actions.scroll-width > div.flex-list-view-content > table > tbody > tr.single.tr-inline-edit > td:nth-child(8) > span > div > a > span:nth-child(1)",
                        "action_lostcat" : "#content > div > div > div.main-pane.span8 > div:nth-child(2) > div.main-content > div:nth-child(2) > div.flex-list-view.left-actions.right-actions.scroll-width > div.flex-list-view-content > table > tbody > tr.single.tr-inline-edit > td:nth-child(15) > span > div > a > span:nth-child(1)", 
                        "action_lostcat_span" : "#content > div > div > div.main-pane.span8 > div:nth-child(2) > div.main-content > div:nth-child(2) > div.flex-list-view.left-actions.right-actions.scroll-width > div.flex-list-view-content > table > tbody > tr.single.tr-inline-edit > td:nth-child(15) > span" ,
                        "action_rea_los_span" : "#content > div > div > div.main-pane.span8 > div:nth-child(2) > div.main-content > div:nth-child(2) > div.flex-list-view.left-actions.right-actions.scroll-width > div.flex-list-view-content > table > tbody > tr.single.tr-inline-edit > td:nth-child(16) > span",
                        "action_rea_los" : "#content > div > div > div.main-pane.span8 > div:nth-child(2) > div.main-content > div:nth-child(2) > div.flex-list-view.left-actions.right-actions.scroll-width > div.flex-list-view-content > table > tbody > tr.single.tr-inline-edit > td:nth-child(16) > span > div > a > span:nth-child(1)",
                        "action_cancel" : "#content > div > div > div.main-pane.span8 > div:nth-child(2) > div.main-content > div:nth-child(2) > div.flex-list-view.left-actions.right-actions.scroll-width > div.flex-list-view-content > table > tbody > tr.single.tr-inline-edit > td:nth-child(1) > span > div:nth-child(3) > span > a",
                        "create_oppty" : "#select2-drop > ul:nth-child(3) > li > div",
                        "create_oppty_" : "#drawers > div.drawer.active > div > div.main-pane.span8 > div:nth-child(1) > div > h1 > div > span.fieldset.actions.selection-headerpane > span > a"
                }
}